sudo: required
language: java
jdk:
- openjdk11
services:
- docker
cache:
  directories:
  - $HOME/.m2
env:
  global:
  # AWS_ACCESS_KEY_ID
  - secure: "0Q5Wx3iPmk3ENq+dyILhH9+kp0/UvBVnLJw/L+N90wXWLJxvFF0T0fPY7SNd3ZbmzjPOHtFlj2/ymC7n/IL19wr35pTR0MQ8QjapXHflCWUPG2lA25+3pusBesY/F3BKQZlCM/zg1n0RjskgnJgkVHfd1poIxH3ajFw/zdMh8HfbHwYB1Ls4eEXCtw89HfC3fFPPdyUEESyz6ErBqrXEngm5qc9jYTUo7eTkOFoFHmuXSICmYeDg12e4dFG5sFah27Jrh2dEA6/xwNqpD0PzFhn0d7YaczU4jtznVT7NF+wlASgjI99ioe9abDoLTvbDdmpm/lOomESwLDr6eeog/rJRwTZTyzdknqNG9nDkwJCcKrQ/e7T+UupkPv+hnEAGCj8ZjKMvYrwTPDPKr1HHlGNQ4MVgByOf5wQMp1qWPFFqpM/cz2dona9n/EnLIIM9agzMxE8mGLx5zS+FUReFhqvwom9EspmqdGX9NebJ5CSL7XuZLGPmRZhLypXyPAxfK3YYyoj4fMHwfgnZfAwnTTGt1gWGGR+XT1w2+3aa4laMNmNzNxGHapxKG2m9CtA+fjDKh7NXaA398V4QC446JpZUM6NSrNu7TEjqZvPhB9fDYZ90CSYKd6kDSXuDsAuNpvCzjWIFU34Zod38XDTJCTu6KQbY3CVxiGYU7I/iq5A="
  # AWS_SECRET_ACCESS_KEY
  - secure: "clWIHNM0M1JDJ6OeMTWlEAnPcT+Z15k+QQ0oI8mV6FGlKUn8OZel84JwmMCCxEvSqwQ8RkLFPQ256QvRMPCszJ45Zlut8uIeC0c02Kdgt05vUq4q0mgjbuT8RGjfMjgIheDS1zbISKF7N8Ydn70Jbh1g0xNp/lesHeFMTAy9MRnQtJp6khUnPsSDmfx0kvaoTld6u5DRG3cEVyVi6VuK/aXkeqL/q2WNdnKjrH2g+DOPJ4drXZhJDJKuekFSzNyuaTD6AEOpAR6TEs4J1NDwcW5s/qMESG1JV14Y4lQzpy3Ee+B9AP2K/nLkyYQ97toD+/XsG75NGADEI7AQD/AyZ38cf2YXbFHSiV9UtYwwhmV6osxU0pN/7o/5+7ra16GhnwVAhiBjlpKF9UuuLXfzwcE2TPVWXAS9tXCWv7kwbCtO1N4gVb/mvyd1EE4tYBOj1nS61YXaQkPTer2o6Nn9bVn1P2cdq71cdUyGRycd2Ox8j3c6DFUbcrYWz8v4ILenGZJ6YgjFEtc/R5h/Sz5xo2F6LQslxiZKLeUtVmRMS2BFNBRSLU7fr6PaUUntrP8Xt21oAYw3FvRMXisoEON/C1OWYbIC47RA9PKWz3SQSWSGeCeJV0zpTpgg13ySrYC1/qx4eghrQ6aZGGZj7JE1U2RORoHjSOlR2t1AbP0gqgc="

install:
- git clone https://github.com/Opetushallitus/ci-tools.git
- source ci-tools/common/setup-tools.sh
- export ARTIFACT_NAME="ohjausparametrit"

script:
- mvn clean spotless:check package -B -Dbranch=${TRAVIS_BRANCH} -Drevision=${TRAVIS_COMMIT} -DbuildNumber=${TRAVIS_BUILD_NUMBER}

- mv target/ohjausparametrit.jar $DOCKER_BUILD_DIR/artifact/${ARTIFACT_NAME}.jar
- cp -vr src/main/resources/oph-configuration $DOCKER_BUILD_DIR/config/

- export BASE_IMAGE="baseimage-fatjar-openjdk11:master"
- ./ci-tools/common/pull-image.sh
- ./ci-tools/build/build-fatjar.sh $ARTIFACT_NAME

deploy:
  provider: script
  script: ./ci-tools/build/upload-image.sh $ARTIFACT_NAME
  on:
    all_branches: true
