sudo: required
language: java
jdk:
- openjdk11
services:
- docker
cache:
  directories:
  - $HOME/.m2
env:
  global:
  # AWS_ACCESS_KEY_ID
  - secure: "KM7ZFmGHUfsKZa4KvfRnr+tpt2bU1x4hcKMM4UqolnUDQApkvX+6eEROs2dDf9GHby33fQKcHQWA3Fbcs1yOEUuZSKRhUcOwVlYtW27oXWArMsTw+f/73aOiXuzJAlfxktroCzLmVxhLe8KT7Lm6emQYuqTVTPg2Q1/D+7ySmZwqOxv1s4MZy9xIUtQfApSo0gzIVfb8dOg/NIwbTOheAM+NO6eMALWqOYRaOa/M4davuY4rE4QeeMII2WAy/TfrLp8iueW1m+3PHSJ1tLhhhat4QWr9TAAFa5VQctOeQAzP1VZ0ZVvDzG62xvDNmlcFSndY19xjLlNBsb9L4EdwLx9V51XftjEkTDvkcDHGxFHTH41z9JSmlinBw/TXaOGfmPdHlIAN69PI6stbI9tRqfIhqYyLjhMQFzDQPo4WhA7D4chXNzl5twvje9ahZhHrFlLnvRHi1RI6zWA02tbbQxyF+LN2RJQCpEmBueWgCBK+zZvuI9MXAOA5UmXFklq6BNeLBmOsg1wQWNaW817GoeIYs5ognwXDzHwnTAcOL1gs83V+lHIngGwQ5FNAE9nbyqQUoPUNa39EXfF9sKQ6j8uGPrTFx8RfRlr60PjdA1zqI5pk4R2SM8qfnSr/izdsngPKb8iZ8BDX9YuL3bIhtGNSFogWHYGCH1iXrLT818k="
  # AWS_SECRET_ACCESS_KEY
  - secure: "WL0Q0ZUS2MoyCuvlkp+1WY95qli8hCGj5FYLZYRu2NuDWo+hpdktqfnKRydDwsEXP1mb+47cGtuYto+/T6XVcvM4JDgEDQ+0EQkdsx99MMGi5MdKTQKjEcH7FRyeUjnoIGnhPVwF4eLdcfuvS/ljyGMFp8swf/serEn16R65pelvG+x9g4PGCh5JmM6WbnPIl/z11udSKC/NeFE1YkkKB7Siuy5CeOWveY7TZIfWfZzlpTPJ/c4vT4xeGstbUiS6VvbPtcpeBSgcAW72t8xQdEFCek5T0LUpL5663C6sMTYAyfMsTT4BsgoZz5E5AJoeoZwHD2mffsiv6KxQiNpvXxuZSOBAzASAmHpSODBvp6m540VnGa18h6jJ8+HVhXlOF6mPzuws5Jt3rbksUbnwponPALdKllBC+GN4HlZ8DvUZYOcTLb+hLkEGAEfyENEYd1iHm641GpJGoFVK0mesZPc3Z9eCBrn5ZLn46DgKYoqwcScNtKqeo31fDAteh5vzeuCymwXAFzFWKlQJIC92BHNCJZ5Pd/EJY8gd18Tzr0agjCqpYP5mQ09bR1GENBdp00NDnJ8V/xZRzEMsinCb3Egwj2+U6uG2uLuCEYYKt50I+wr4em5oJ7yD3g8E9I41OXKXeAjW/d6wbdJpvEUoDlYxO0kK9mS80OV6wlF+Rvo="

install:
- git clone https://github.com/Opetushallitus/ci-tools.git
- source ci-tools/common/setup-tools.sh
- export ARTIFACT_NAME="ohjausparametrit"

script:
- mvn clean install -B -Dbranch=${TRAVIS_BRANCH} -Drevision=${TRAVIS_COMMIT} -DbuildNumber=${TRAVIS_BUILD_NUMBER}

- mv ohjausparametrit-service/target/ohjausparametrit-service.jar $DOCKER_BUILD_DIR/artifact/${ARTIFACT_NAME}.jar
- cp -vr src/main/resources/oph-configuration $DOCKER_BUILD_DIR/config/

- export BASE_IMAGE="baseimage-fatjar-openjdk11:master"
- ./ci-tools/common/pull-image.sh
- ./ci-tools/build/build-fatjar.sh $ARTIFACT_NAME

deploy:
  provider: script
  script: ./ci-tools/build/upload-image.sh $ARTIFACT_NAME
  on:
    all_branches: true
