spring:
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      # https://hibernate.atlassian.net/browse/HHH-12368
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.id.db_structure_naming_strategy: single
      hibernate.id.new_generator_mappings: true
      hibernate.integration.envers.enabled: true
      org.hibernate.envers.store_data_at_delete: true
