logging.level.org:
  springframework.web: info
  hibernate: info

spring:
  main:
    banner-mode: "off"
  mandatory-file-encoding: UTF-8
  profiles.active: default
  session:
    store-type: jdbc
  jackson:
    serialization:
      write-dates-as-timestamps: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5489/ohjausparametrit?ApplicationName=ohjausparametrit-service
    username: oph
    password: oph
    hikari:
      maximum-pool-size: 10
      connection-timeout: 10000
      max-lifetime: 900000
  flyway:
    enabled: true
    table: schema_version
    out-of-order: true
    # Only for initial production release, set false afterwards
    baseline-on-migrate: false
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      ddl-auto: validate
      use-new-id-generator-mappings: true
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      # https://hibernate.atlassian.net/browse/HHH-12368
      hibernate.jdbc.lob.non_contextual_creation: true

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true

server:
  servlet:
    context-path: /ohjausparametrit-service
    session:
      cookie:
        name: JSESSIONID
  port: 8080

ohjausparametrit:
  uses-ssl-proxy: false
  disable-same-site-cookie: false

cas:
  service: http://localhost:${server.port}/ohjausparametrit-service
  send-renew: false
  key: ohjausparametrit-service

host:
  #host-virkailija: localhost:${server.port}
  #host-cas: localhost:${server.port}
  #host-alb: http://localhost:${server.port}
  host-virkailija: virkailija.testiopintopolku.fi
  host-cas: virkailija.testiopintopolku.fi
  host-alb: https://virkailija.testiopintopolku.fi

